server:
  port: 80
spring:
  mvc:
    servlet:
      path: /api
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/book
    password: 2002
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
jwt:
  secretKey: SupperKey
  expireTime: 864000000
